### ISSUE TITLE
Graphite: NPE on shutdown

### ISSUE THREAD

**Issue by KrauseStefan** [gatling/gatling#3352]
I'm now experiencing this issue as well.

Setup:

Win 8.1
Gatling 2.2.5
Async websockets checks are used, together with http
Test target is on the same machine
As you can see in the screenshot below this happens after the simulation is completed.
The last thing the test does is

```
exec(
  exec(ws("End Async Check", socketName).reconciliate),
  exec(ws("Close WebSocket", socketName).close)
)
```
It does not reproduce every time though, but pretty often.

![image](https://user-images.githubusercontent.com/1446336/30367476-9b1a2148-986e-11e7-8551-1cd269a78030.png)

I managed to put a breakpoint on the line that throws this error, I don't know the issue though.
Below is a screenshot with variable values, let me know if there is anything I can try, I will upgrade my gatling version soon but as I see the changelog this is not fixed

![image](https://user-images.githubusercontent.com/1446336/30367407-6f220e98-986e-11e7-9935-8b4d1d238d1d.png)

This is a duplicate of #3052 but it is closed and it seems no one is looking at it :)

**Comment by slandelle** [comment]
Have a look at the stacktrace: this crash happens in the Graphite DataWriter when Gatling shuts down. It has nothing to do with HTTP nor WebSockets. I suspect you use something like maxDuration that forcefully closes Gatling, and can cause some race conditions on shut down.

The HTML reports are still being generated, so this is more an inconvenience than a critical issue and I don't think me or the other Gatling Corp people will invest time on this.

Then, we'd love a contribution!

**Comment by slandelle** [comment]
I suspect one should just try to catch the exception in the TcpSender and ignore it. Gatling is being shutdown and there's nothing to do to try to recover.

**Comment by KrauseStefan** [comment]
Yes I have the graphite connection enabled, (however influxDB is not started).
And you are right the test seems to work correctly without any issues, except for this log message.

Thank you for your hint, I'll see if I can find time to try and create a pull request.

**Comment by slandelle** [comment]
Closing due to lack of activity. Moreover, such issue wasn't reported since then, so it's possible it was fixed in Akka (who knows).

**Comment by owlmylove** [comment]
Not fixed yet, its so confusing, as the test runs ok, but there is an error
